name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version'
        required: true
        default: '8.3'
      wavelog_version:
        description: 'wavelog version'
        required: true
        default: '1.3.1'
      image_tag:
        description: 'Which tag to associate the image with'
        required: false
        default: 'latest'

jobs:
  build:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    name: 'build'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build container image
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.10.1"
          verb: call
          module: '.'
          args: 'build --php-version=8.3 --wavelog-version=1.3.1'

  build-and-push:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    env:
      CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and push container image
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.10.1"
          verb: call
          module: '.'
          args: >-
            build \
              --php-version="${{ inputs.php_version }}" \
              --wavelog-version="${{ inputs.wavelog_version }}" \
              with-registry-auth \
                --address="ghcr.io" \
                --username="${{ github.actor }}" \
                --secret="env:CI_REGISTRY_TOKEN" \
              publish \
                --address="ghcr.io/philipreinken/wavelog-docker:${{ inputs.image_tag }}"